# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import csv
import json
import time
import traceback
from multiprocessing import freeze_support
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


ROOT = Path(__file__).resolve().parent
DEFAULT_DATA = ROOT / "datasets" / "data.yaml"
DEFAULT_PROJECT = ROOT / "runs" / "ablation"
GENERATED_MODEL_DIR = ROOT / "ultralytics" / "cfg" / "models" / "v8" / "ablation_generated"

# A: PPAP-EMA, B: KDE hypergraph fusion, C: RGCU + CLAG top-down fusion.
VARIANTS: Dict[str, Tuple[bool, bool, bool]] = {
    "base": (False, False, False),
    "A": (True, False, False),
    "B": (False, True, False),
    "C": (False, False, True),
    "AB": (True, True, False),
    "AC": (True, False, True),
    "BC": (False, True, True),
    "ABC": (True, True, True),
}


def add_layer(layers: List[list], source, repeats: int, module: str, args: list) -> int:
    layers.append([source, repeats, module, args])
    return len(layers) - 1


def add_head(backbone: List[list], head: List[list], source, repeats: int, module: str, args: list) -> int:
    head.append([source, repeats, module, args])
    return len(backbone) + len(head) - 1


def build_model_cfg(use_ppap: bool, use_hypergraph: bool, use_clag_rgcu: bool) -> dict:
    backbone: List[list] = []

    add_layer(backbone, -1, 1, "Conv", [64, 3, 2])       # 0-P1/2
    add_layer(backbone, -1, 1, "Conv", [128, 3, 2])      # 1-P2/4
    add_layer(backbone, -1, 3, "C2f", [128, True])       # 2
    add_layer(backbone, -1, 1, "Conv", [256, 3, 2])      # 3-P3/8
    p3 = add_layer(backbone, -1, 6, "C2f", [256, True])  # 4
    add_layer(backbone, -1, 1, "Conv", [512, 3, 2])      # 5-P4/16
    p4 = add_layer(backbone, -1, 6, "C2f", [512, True])  # 6
    add_layer(backbone, -1, 1, "Conv", [1024, 3, 2])     # 7-P5/32
    p5_pre = add_layer(backbone, -1, 3, "C2f", [1024, True])  # 8

    if use_ppap:
        add_layer(backbone, -1, 1, "PPAPEMA", [8, 0.05, 8, 64, 1])

    sppf = add_layer(backbone, -1, 1, "SPPF", [1024, 5])

    if use_hypergraph:
        sources = [2, p3, p4, p5_pre, sppf]
        r3 = add_layer(backbone, sources, 1, "KDEHyperGraphFusion", [256, 1, 48, 0.1])
        r4 = add_layer(backbone, sources, 1, "KDEHyperGraphFusion", [512, 2, 48, 0.1])
        r5 = add_layer(backbone, sources, 1, "KDEHyperGraphFusion", [1024, 4, 48, 0.1])
    else:
        r3, r4, r5 = p3, p4, sppf

    head: List[list] = []
    if use_clag_rgcu:
        x = add_head(backbone, head, [r5, r4], 1, "CLAGRGCUFuse", [512])
        p4_td = add_head(backbone, head, -1, 3, "C2f", [512])
        x = add_head(backbone, head, [p4_td, r3], 1, "CLAGRGCUFuse", [256])
        p3_out = add_head(backbone, head, -1, 3, "C2f", [256])
    else:
        x = add_head(backbone, head, -1, 1, "nn.Upsample", [None, 2, "nearest"])
        x = add_head(backbone, head, [-1, r4], 1, "Concat", [1])
        p4_td = add_head(backbone, head, -1, 3, "C2f", [512])
        x = add_head(backbone, head, -1, 1, "nn.Upsample", [None, 2, "nearest"])
        x = add_head(backbone, head, [-1, r3], 1, "Concat", [1])
        p3_out = add_head(backbone, head, -1, 3, "C2f", [256])

    add_head(backbone, head, -1, 1, "Conv", [256, 3, 2])
    add_head(backbone, head, [-1, p4_td], 1, "Concat", [1])
    p4_out = add_head(backbone, head, -1, 3, "C2f", [512])

    add_head(backbone, head, -1, 1, "Conv", [512, 3, 2])
    add_head(backbone, head, [-1, r5], 1, "Concat", [1])
    p5_out = add_head(backbone, head, -1, 3, "C2f", [1024])

    add_head(backbone, head, [p3_out, p4_out, p5_out], 1, "Detect", ["nc"])

    return {
        "nc": 80,
        "scales": {
            "n": [0.33, 0.25, 1024],
            "s": [0.33, 0.50, 1024],
            "m": [0.67, 0.75, 768],
            "l": [1.00, 1.00, 512],
            "x": [1.00, 1.25, 512],
        },
        "backbone": backbone,
        "head": head,
    }


def dump_model_yaml(name: str, use_ppap: bool, use_hypergraph: bool, use_clag_rgcu: bool) -> Path:
    GENERATED_MODEL_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_MODEL_DIR / f"yolov8n_ablation_{name.lower()}.yaml"
    cfg = build_model_cfg(use_ppap, use_hypergraph, use_clag_rgcu)
    header = (
        "# Auto-generated by ablation.py\n"
        f"# Variant {name}: A(PPAP-EMA)={use_ppap}, "
        f"B(KDE-HyperGraph)={use_hypergraph}, C(RGCU+CLAG)={use_clag_rgcu}\n"
    )
    # JSON is valid YAML 1.2 and avoids needing PyYAML before training dependencies are installed.
    text = json.dumps(cfg, indent=2)
    path.write_text(header + text, encoding="utf-8")
    return path


def parse_pretrained(value: str):
    lower = str(value).strip().lower()
    if lower in {"true", "1", "yes", "y"}:
        return True
    if lower in {"false", "0", "no", "n"}:
        return False
    if lower in {"none", "null"}:
        return None
    return value


def str2bool(value) -> bool:
    if isinstance(value, bool):
        return value
    lower = str(value).strip().lower()
    if lower in {"true", "1", "yes", "y", "on"}:
        return True
    if lower in {"false", "0", "no", "n", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"expected a boolean value, got '{value}'")


def select_variants(items: Iterable[str]) -> List[str]:
    requested = list(items)
    if not requested or requested == ["all"]:
        return list(VARIANTS.keys())

    expanded: List[str] = []
    for item in requested:
        key = item.strip()
        lower = key.lower()
        if lower in {"all", "full"}:
            expanded.extend(VARIANTS.keys())
        elif lower == "six":
            expanded.extend(["A", "B", "C", "AB", "AC", "BC"])
        else:
            canonical = key.upper() if key.upper() in VARIANTS else key.lower()
            if canonical not in VARIANTS:
                raise ValueError(f"unknown variant '{item}', valid values: {', '.join(VARIANTS)}")
            expanded.append(canonical)

    result: List[str] = []
    for item in expanded:
        if item not in result:
            result.append(item)
    return result


def get_device_arg(device: str):
    if device != "auto":
        return device
    import torch

    return 0 if torch.cuda.is_available() else "cpu"


def empty_cuda_cache() -> None:
    try:
        import torch

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def append_summary(summary_csv: Path, row: dict) -> None:
    summary_csv.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "variant",
        "use_ppap",
        "use_hypergraph",
        "use_clag_rgcu",
        "status",
        "model_yaml",
        "save_dir",
        "seed",
        "error",
    ]
    exists = summary_csv.exists()
    with summary_csv.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        if not exists:
            writer.writeheader()
        writer.writerow(row)


def run_variant(name: str, model_yaml: Path, args, seed: int):
    from ultralytics import YOLO

    model = YOLO(str(model_yaml))
    return model.train(
        data=str(args.data),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        workers=args.workers,
        device=get_device_arg(args.device),
        project=str(args.project),
        name=f"{args.name_prefix}_{name.lower()}_seed{seed}",
        exist_ok=args.exist_ok,
        pretrained=parse_pretrained(args.pretrained),
        save=True,
        save_period=args.save_period,
        cache=args.cache,
        patience=args.patience if args.patience is not None else args.epochs,
        seed=seed,
        deterministic=args.deterministic,
        verbose=True,
        resume=False,
        amp=args.amp,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run full A/B/C ablation for PPAP-EMA, KDE-HyperGraph, and RGCU+CLAG.")
    parser.add_argument("--variants", nargs="*", default=["all"], help="all, six, base, A, B, C, AB, AC, BC, ABC")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT)
    parser.add_argument("--name-prefix", default="ablation")
    parser.add_argument("--epochs", type=int, default=500)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--device", default="auto", help="'auto', 'cpu', or CUDA index such as '0'")
    parser.add_argument("--seed", type=int, default=3408)
    parser.add_argument("--pretrained", default="True", help="True, False, None, or a checkpoint path")
    parser.add_argument("--save-period", type=int, default=10)
    parser.add_argument("--patience", type=int, default=None)
    parser.add_argument("--cache", action="store_true")
    parser.add_argument("--exist-ok", action="store_true")
    parser.add_argument("--deterministic", type=str2bool, default=True)
    parser.add_argument("--amp", type=str2bool, default=True)
    parser.add_argument("--dry-run", action="store_true", help="Only generate YAML files and print the run plan.")
    args = parser.parse_args()

    variants = select_variants(args.variants)
    args.project.mkdir(parents=True, exist_ok=True)
    summary_csv = args.project / "ablation_summary.csv"

    print("A = PPAP-EMA, B = KDE-HyperGraph, C = RGCU+CLAG")
    print("Data:", args.data)
    print("Project:", args.project)
    print("Variants:", ", ".join(variants))

    for offset, name in enumerate(variants):
        use_ppap, use_hypergraph, use_clag_rgcu = VARIANTS[name]
        model_yaml = dump_model_yaml(name, use_ppap, use_hypergraph, use_clag_rgcu)
        seed = args.seed + offset

        print("\n" + "=" * 90)
        print(f"Variant {name}: A={use_ppap}, B={use_hypergraph}, C={use_clag_rgcu}")
        print("Model YAML:", model_yaml)
        print("Seed:", seed)
        print("=" * 90)

        if args.dry_run:
            continue

        row = {
            "variant": name,
            "use_ppap": use_ppap,
            "use_hypergraph": use_hypergraph,
            "use_clag_rgcu": use_clag_rgcu,
            "status": "failed",
            "model_yaml": str(model_yaml),
            "save_dir": "",
            "seed": seed,
            "error": "",
        }
        try:
            results = run_variant(name, model_yaml, args, seed)
            save_dir = getattr(getattr(results, "trainer", None), "save_dir", "")
            row["save_dir"] = str(save_dir)
            row["status"] = "ok"
            append_summary(summary_csv, row)
            empty_cuda_cache()
            time.sleep(5)
        except Exception as exc:
            row["error"] = repr(exc)
            append_summary(summary_csv, row)
            traceback.print_exc()
            empty_cuda_cache()
            time.sleep(5)


if __name__ == "__main__":
    freeze_support()
    main()
